# Cálculo de CSP función "Solar Trough Calcs"

In [1]:
import CombiCSP.solar_trough as ST
import CombiCSP.solar_system_location as SL
import CombiCSP.SolarGeometry as SG

In [2]:
import random
# Generar valores aleatorios para mer y dt_gmt
mer = random.uniform(0, 360)
dt_gmt = random.uniform(-12, 12)

# Crear una instancia de SolarTroughCalcs con valores aleatorios para mer y dt_gmt
solar_trough = ST.SolarTroughCalcs(0.88, 1800, 25, 18, 0.07, 5.76, SL.SolarSystemLocation(lat=35.015, lon=25.755, mer=mer, dt_gmt=dt_gmt))

## Salida de Datos

In [3]:
solar_trough.print_system_summary()


--------  System Parameters
-> Focal Lentth     (foc_len) = 0.88  
-> Number of units  (   N   ) = 1800      
-> Unit length      (   L   ) =  25 
-> Unit spacing?    (   Ws  ) = 18 
-> Receiver width   (   Wr  ) = 0.07
-> Collector width  (   Wc  ) = 5.76
--------  Derived Quantities
-> Collector area   (   Ac  ) = 259200.0
-> Receiver area    (   Ar  ) = 3150.0000000000005
-> Concetration f   (   Cg  ) = 82.28571428571428
        


In [4]:
import pandas as pd
import numpy as np

# Asumiendo un valor promedio de irradiación solar de 800 W/m^2
Ib = pd.Series(np.random.rand(8760))

# Valores opcionales
Tr = 318

## Cálculos de funcionamiento de Este a Oeste

In [5]:
# Obtener el objeto OutputContainer con los resultados
resultados = solar_trough.perform_calcs_EW(Ib, Tr, SL.HOYS_DEFAULT)

# Acceder a los valores específicos dentro del objeto OutputContainer
datos_calculados = resultados.data
area_heliostatica = resultados.A_helio
Ctow = resultados.Ctow

# Imprimir los valores
print("Datos calculados:", datos_calculados)
print("Área heliostática:", area_heliostatica)
print("Ctow:", Ctow)

Datos calculados: 0      -7.449119
1      -7.460327
2      -7.461625
3      -7.454700
4      -7.450093
          ...   
8755   -7.468824
8756   -7.459894
8757   -7.460488
8758   -7.445827
8759   -7.457147
Length: 8760, dtype: float64
Área heliostática: 259200.0
Ctow: 82.28571428571428


## $cos(\theta)$ de Este a Oeste

In [6]:
costheta_EW = solar_trough.costhetai_EW(SL.HOYS_DEFAULT)
costheta_EW

array([0.743085  , 0.58499251, 0.43523543, ..., 0.9918728 , 0.95987856,
       0.87419058])

## Cálculos de funcionamiento de Norte a Sud

In [7]:
resultados1 = solar_trough.perform_calcs_NS(Ib, Tr, SL.HOYS_DEFAULT)
# Acceder a los valores específicos dentro del objeto OutputContainer
datos_calculados1 = resultados1.data
area_heliostatica1 = resultados1.A_helio
Ctow1 = resultados1.Ctow

# Imprimir los valores
print("Datos calculados:", datos_calculados1)
print("Área heliostática:", area_heliostatica1)
print("Ctow:", Ctow1)

Datos calculados: 0      -7.438871
1      -7.447201
2      -7.439876
3      -7.416277
4      -7.420199
          ...   
8755   -7.467656
8756   -7.459587
8757   -7.460716
8758   -7.445017
8759   -7.454220
Length: 8760, dtype: float64
Área heliostática: 259200.0
Ctow: 82.28571428571428


## $cos(\theta)$ de Norte a Sud

In [8]:
costheta_NS = solar_trough.costhetai_NS(SL.HOYS_DEFAULT)
costheta_NS

array([0.99873588, 0.99832908, 0.9830427 , ..., 0.97958707, 0.98339305,
       0.99176581])

## $\theta_{i}$

In [9]:
incl = 90
azim = 0
theta_i = solar_trough.thetai(SL.HOYS_DEFAULT, incl, azim)
theta_i

array([1.52050941, 1.51297956, 1.38637594, ..., 1.36839692, 1.38829633,
       1.44237889])

## Modificador del ángulo de incidencia de la placa solar

In [10]:
IAM_tro = solar_trough.IAM_tro(SL.HOYS_DEFAULT)
IAM_tro

array([1.00642747, 1.00651471, 1.00780416, ..., 1.00796011, 1.0077871 ,
       1.0072751 ])

## Potencia total del sistema parabólico

In [11]:
import math
nG = 0.97
costheta = math.cos(theta_i[0])
di_sst = solar_trough.di_sst(SL.HOYS_DEFAULT, Ib, costheta, Tr, nG)
di_sst

0      -7.476890
1      -7.477308
2      -7.476909
3      -7.475584
4      -7.475595
          ...   
8755   -7.478334
8756   -7.477917
8757   -7.477971
8758   -7.477173
8759   -7.477654
Length: 8760, dtype: float64

## Energía incidente en el sistema

In [12]:
incident_energy_on_system = solar_trough.incident_energy_on_system('NS', Ib, SL.HOYS_DEFAULT)
incident_energy_on_system

0       0.566138
1       0.448338
2       0.551931
3       0.885659
4       0.830193
          ...   
8755    0.159074
8756    0.273187
8757    0.257212
8758    0.479234
8759    0.349080
Length: 8760, dtype: float64

## Nueva Instancia

In [13]:
solar_location = SL.SolarSystemLocation(lat=35.015, lon=25.755, mer=5, dt_gmt=0)

# Modificamos algunos atributos de 'solar_trough' usando el método 'mutate'
nueva_instancia = solar_trough.mutate(foc_len=100, N=200, slobj=solar_location)
nueva_instancia.costhetai_EW(SL.HOYS_DEFAULT)

array([0.79649662, 0.64560417, 0.48645136, ..., 0.98921985, 0.97846807,
       0.91216944])

# Funciones Independientes

## Modificador del ángulo de incidencia de la placa solar

In [14]:
IAM_tro = ST.IAM_tro(SL.HOYS_DEFAULT)
IAM_tro

array([1.00797954, 1.00766053, 1.00697884, ..., 1.00696434, 1.00763131,
       1.00793591])

In [15]:
IAM_tro2 = ST.IAM_tro2(SL.HOYS_DEFAULT)
IAM_tro2

array([0.99894507, 0.99890795, 0.9988361 , ..., 0.99883465, 0.99890468,
       0.99893983])

In [16]:
IAM_tro3 = ST.IAM_tro3(SL.HOYS_DEFAULT)
IAM_tro3

array([0.99917745, 0.99914635, 0.9990859 , ..., 0.99908469, 0.9991436 ,
       0.99917306])

In [17]:
foc_len = 1
area = 2
L = 1


IAM_tro4 = ST.IAM_tro4(SL.HOYS_DEFAULT, foc_len, area, L,)
IAM_tro4

array([0.97416524, 0.97348066, 0.97217961, ..., 0.97215385, 0.97342075,
       0.97406804])

In [18]:
costheta_i = ST.costhetai(SL.HOYS_DEFAULT)
costheta_i

array([0.97912287, 0.98583564, 0.99502974, ..., 0.99516442, 0.98636181,
       0.98015434])

In [19]:
costheta_EW = ST.costhetai_EW(SL.HOYS_DEFAULT)
costheta_EW

array([0.98367892, 0.92414056, 0.81399477, ..., 0.82928278, 0.93324832,
       0.98640678])

In [20]:
costheta_NS = ST.costhetai_NS(SL.HOYS_DEFAULT)
costheta_NS

array([0.97912287, 0.98583564, 0.99502974, ..., 0.99516442, 0.98636181,
       0.98015434])

In [21]:
Wc = 1
N = 1
Ac = ST.Ac(Wc, L, N)
Ac

1

In [22]:
Wr = 1
ST.Ar(Wr, L, N)

1

In [23]:
ST.Cg_tro(Wc, Wr, L, N)

1.0

In [24]:
Ws = 1
ST.di_sst(Ib, costheta_i, IAM_tro,Tr, Wc, Wr, Ws, L, N, nG)

0      -0.002374
1      -0.002374
2      -0.002374
3      -0.002374
4      -0.002374
          ...   
8755   -0.002374
8756   -0.002374
8757   -0.002374
8758   -0.002374
8759   -0.002374
Length: 8760, dtype: float64

In [29]:
ST.CSCUL(SL.HOYS_DEFAULT)

0.05715885685940374

In [34]:
Tfi = 10
fname = 'tmy_35.015_25.755_2005_2020.csv'
ST.CSCP(Tfi, SL.HOYS_DEFAULT, fname)

c:\Users\heber\Desktop\Combi_CSP\CombiCSP\solar_trough.py:556: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pvgis_data = pd.read_csv(fname, header=16, nrows=8776-16, parse_dates=['time(UTC)'], engine='python')


0       9.998077
1       9.998077
2       9.998077
3       9.998077
4       9.998077
          ...   
8755    9.998077
8756    9.998077
8757    9.998077
8758    9.998077
8759    9.998077
Name: Gb(n), Length: 8760, dtype: float64